### ISSUE TITLE
App won't start because bg task setup fails ("not enough quotas available")

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#130]
```
2018-03-03T18:49:36 [UI] [Error] [Signal_Windows.App] UnhandledException System.Exception occured (Nicht genÃ¼gend Quoten verfÃ¼gbar, um diesen Befehl zu verarbeiten. (Exception from HRESULT: 0x80070718)):
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
   at Signal_Windows.App.<OnLaunched>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

My bg task appears to be stuck:
```
2018-03-03T18:50:40 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Confirming message 2118793391972421806
2018-03-03T18:50:40 [BG] [Trace] [libsignalservice.SignalServiceMessagePipe] ReadBlocking()
2018-03-03T18:50:40 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Calling callback with message 4773343642776763475
2018-03-03T18:50:40 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locking
2018-03-03T18:50:40 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locked
2018-03-03T18:50:40 [BG] [Warning] [Signal_Windows.Lib.IncomingMessages] HandleMessage() received unrecognized message
2018-03-03T18:50:40 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() released
2018-03-03T18:50:40 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Confirming message 4773343642776763475
2018-03-03T18:50:40 [BG] [Trace] [libsignalservice.SignalServiceMessagePipe] ReadBlocking()
2018-03-03T18:50:40 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Calling callback with message 5285564043250303080
2018-03-03T18:50:40 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locking
2018-03-03T18:50:40 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locked
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() released
2018-03-03T18:50:41 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Confirming message 5285564043250303080
2018-03-03T18:50:41 [BG] [Warning] [Signal_Windows.Lib.IncomingMessages] HandleIncomingMessages() failed: System.NullReferenceException occured (Object reference not set to an instance of an object.):
   at Signal_Windows.RC.SignalBackgroundTask.Handle_SignalMessageEvent(Object sender, SignalMessageEventArgs e)
   at Signal_Windows.Lib.SignalLibHandle.DispatchHandleMessage(SignalMessage message, SignalConversation conversation)
   at Signal_Windows.Lib.SignalLibHandle.SaveAndDispatchSignalMessage(SignalMessage message, SignalConversation conversation)
   at Signal_Windows.Lib.IncomingMessages.HandleSignalMessage(SignalServiceEnvelope envelope, SignalServiceContent content, SignalServiceDataMessage dataMessage, Boolean isSync, Int64 timestamp)
   at Signal_Windows.Lib.IncomingMessages.HandleMessage(SignalServiceEnvelope envelope)
   at Signal_Windows.Lib.IncomingMessages.OnMessage(SignalServiceMessagePipeMessage message)
   at libsignalservice.SignalServiceMessagePipe.ReadBlocking(IMessagePipeCallback callback)
   at Signal_Windows.Lib.IncomingMessages.HandleIncomingMessages()
2018-03-03T18:50:41 [BG] [Trace] [libsignalservice.SignalServiceMessagePipe] ReadBlocking()
2018-03-03T18:50:41 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Calling callback with message 4844744783343808803
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locking
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locked
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() released
2018-03-03T18:50:41 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Confirming message 4844744783343808803
2018-03-03T18:50:41 [BG] [Trace] [libsignalservice.SignalServiceMessagePipe] ReadBlocking()
2018-03-03T18:50:41 [BG] [Debug] [libsignalservice.SignalServiceMessagePipe] Calling callback with message 4745145283629588000
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locking
2018-03-03T18:50:41 [BG] [Trace] [Signal_Windows.Lib.IncomingMessages] OnMessage() locked
```

**Comment by golf1052** [comment]
I figured out a new way of managing background tasks when the app starts,, looks something like this. From what I could find this is a small page file issue, the background task should be lightweight so I'm not entirely sure what it could be,
```csharp
foreach (var task in BackgroundTaskRegistration.AllTasks)
{
    Debug.WriteLine(task.Key.ToString());
    Debug.WriteLine(task.Value.Name);
    Debug.WriteLine(task.Value.TaskId);
    task.Value.Unregister(false);
}
BackgroundExecutionManager.RemoveAccess();
foreach (var task in BackgroundTaskRegistration.AllTasks)
{
    Debug.WriteLine(task.Key.ToString());
    Debug.WriteLine(task.Value.Name);
    Debug.WriteLine(task.Value.TaskId);
}
var builder = new BackgroundTaskBuilder();
builder.Name = "Class1";
builder.TaskEntryPoint = "RuntimeComponent1.Class1";
builder.SetTrigger(new SystemTrigger(SystemTriggerType.TimeZoneChange, false));
var requestStatus = await BackgroundExecutionManager.RequestAccessAsync();
builder.Register();
```

**Comment by Trolldemorted** [comment]
My device was offline for 2-3 days, so way more than 100 messages were in the queue. I wrapped the bg task part in a try-catch block for now, so that the app starts up again.

**Comment by Trolldemorted** [comment]
Did you test whether that way works? Shall we switch to it before the next release?
