### ISSUE TITLE
message download fails if digest is missing

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#135]
```
2018-04-26T15:21:43 [Error] [Signal_Windows.Lib.SignalLibHandle] HandleSuccessfullDownload failed: Object reference not set to an instance of an object.
   at libsignal.util.ByteUtil.isEqual(Byte[] first, Byte[] second)
   at libsignalservice.SignalServiceMessageReceiver.VerifyMac(Stream stream, HMAC mac, Byte[] theirDigest)
   at libsignalservice.SignalServiceMessageReceiver.DecryptAttachment(SignalServiceAttachmentPointer pointer, Stream cipherStream, Stream plaintextStream)
   at Signal_Windows.Lib.SignalLibHandle.DecryptAttachment(SignalServiceAttachmentPointer pointer, Stream tempStream, Stream downloadStream)
   at Signal_Windows.Lib.SignalLibHandle.<HandleSuccessfullDownload>d__49.MoveNext()
```

**Comment by Trolldemorted** [comment]
3d3d32a77752f0c9d1eaf6d621fed76c79e11a5d
