### ISSUE TITLE
Signal-Windows crashes if you rapidly launch it 2 times

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#142]
```
2018-04-29T02:48:38 [UI] [Information] [Signal_Windows.App] Launching (PreviousExecutionState=ClosedByUser)
2018-04-29T02:48:38 [UI] [Debug] [Signal_Windows.App] C:\Users\Benni\AppData\Local\Packages\2383BenediktRadtke.SignalPrivateMessenger_teak1p7hcx9ga\LocalCache
2018-04-29T02:48:38 [UI] [Trace] [Signal_Windows.Lib.SignalLibHandle] Acquire() locking
2018-04-29T02:48:38 [UI] [Trace] [Signal_Windows.Lib.LibUtils] OpenResetEventSet()
2018-04-29T02:48:38 [UI] [Trace] [Signal_Windows.Lib.LibUtils] System lock locking, sync context = System.Threading.WinRTSynchronizationContext
2018-04-29T02:48:38 [UI] [Trace] [Signal_Windows.Lib.LibUtils] System lock locked
2018-04-29T02:48:38 [UI] [Debug] [Signal_Windows.Lib.SignalLibHandle] Acquire() locked (global and local)
2018-04-29T02:48:38 [UI] [Information] [Signal_Windows.App] Launching (PreviousExecutionState=Running)
2018-04-29T02:48:38 [UI] [Debug] [Signal_Windows.App] C:\Users\Benni\AppData\Local\Packages\2383BenediktRadtke.SignalPrivateMessenger_teak1p7hcx9ga\LocalCache
2018-04-29T02:48:38 [UI] [Error] [Signal_Windows.App] UnhandledException System.NullReferenceException occured (Object reference not set to an instance of an object.):
   at Signal_Windows.App.<OnLaunched>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

**Comment by Trolldemorted** [comment]
Can no longer reproduce
