### ISSUE TITLE
Incoming messages fail (debug log shows InvalidVersionException occured (Unsupported version!))

### ISSUE THREAD

**Issue by mitchcapper** [signal-csharp/Signal-Windows#220]
Crosslinking to library issue for those who might also encounter: 
https://github.com/signal-csharp/libsignal-service-dotnet/issues/43

```
Exception thrown: 'libsignal.InvalidVersionException' in System.Private.CoreLib.dll
2021-02-14T09:36:55 [Warning] [Signal_Windows.Lib.IncomingMessages] HandleIncomingMessages() failed: libsignal.InvalidVersionException occured (Unsupported version!):
   at libsignalservice.messages.SignalServiceEnvelope..ctor(Byte[] ciphertext, String signalingKey)
   at libsignalservice.SignalServiceMessagePipe.<ReadBlocking>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Signal_Windows.Lib.IncomingMessages.<HandleIncomingMessages>d__5.MoveNext()
2021-02-14T09:36:55 [Trace] [libsignalservice.SignalServiceMessagePipe] ReadBlocking()
creating contact test (+15095545544)
2021-02-14T09:37:36 [Trace] [Signal_Windows.Lib.SignalLibHandle] SaveAndDispatchSignalConversation() locking
2021-02-14T09:37:36 [Trace] [Signal_Windows.Lib.SignalLibHandle] SaveAndDispatchSignalConversation() released
2021-02-14T09:37:37 [Debug] [Signal_Windows.ViewModels.MainPageViewModel] ContactsList_SelectionChanged()
2021-02-14T09:37:40 [Trace] [Signal_Windows.Lib.SignalLibHandle] SendMessage() locking
2021-02-14T09:37:40 [Trace] [Signal_Windows.Lib.SignalLibHandle] SendMessage() locked
```

**Comment by golf1052** [comment]
This is resolved with https://github.com/signal-csharp/Signal-Windows/commit/d1cdf07552de94f765c024558e0f6df5e130ca80

**Comment by golf1052** [comment]
Signal Windows 0.3.0 is in the store.
