### ISSUE TITLE
OperationCanceledException when going back on LinkPage

### ISSUE THREAD

**Issue by golf1052** [signal-csharp/Signal-Windows#96]
```
System.OperationCanceledException occurred
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at libsignal.push.ProvisioningSocket.GetProvisioningMessage(IdentityKeyPair tmpIdentity)
   at libsignalservice.SignalServiceAccountManager.FinishNewDeviceRegistration(IdentityKeyPair tempIdentity, String signalingKey, String password, Boolean sms, Boolean fetches, Int32 regid, String name)
   at Signal_Windows.ViewModels.LinkPageViewModel.<>c__DisplayClass17_0.<BeginLinking>b__0() in C:\Users\Sanders\OneDrive\Projects\Signal-Windows\Signal-Windows\ViewModels\LinkPageViewModel.cs:line 94
   at System.Threading.Tasks.Task.Execute()
```

**Comment by Trolldemorted** [comment]
We are cancelling the account manager's token if we click the back button:

```
internal async void BackButton_Click(object sender, BackRequestedEventArgs e)
{
    if (UIEnabled)
    {
        CancelSource.Cancel();
```

but we safely catch it in `BeginLinking`. Did signal crash on your device?

**Comment by golf1052** [comment]
Yes

**Comment by Trolldemorted** [comment]
That is very odd. I just tested it, on my W10 desktop the exception was caught [here](https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows/ViewModels/LinkPageViewModel.cs#L132) and the welcome page appeared.

Did you have a debugger attached?

**Comment by golf1052** [comment]
You're right, I don't know why Visual Studio throws the exception but then it gets handled anyway.
